### PR TITLE
Allow for custom keymap descriptions

### LINKED ISSUE #28: Adding keymap descriptions
Hello, 

is there a way to add keymap descriptions? I can add keymap descriptions for textobjects like this:
```lua
textobjects = {
    select = {
        keymaps = {
            ['af'] = { query = '@function.outer', desc = 'outer function' },
            ['if'] = { query = '@function.inner', desc = 'inner function' },
        },
    },
    move = {
        goto_next_start = {
            [']m'] = { query = '@function.outer', desc = 'next method start' },
        },
        goto_next_end = {
            [']M'] = { query = '@function.outer', desc = 'next method end' },
        },
    },
}
```
Is there also a way for textsubjects?

### PR DESCRIPTION
**Pull request by Subjective**
Resolves #28

### CODE REVIEW

**Review by RRethy — CHANGES_REQUESTED** [review]
This will break backwards compatibility. All existing keymaps using strings will break when `config.query` gets called if a user updates to this version.

**Comment by Subjective** [comment]
@ RRethy, whoops I somehow did not catch that, just fixed it

**Comment by Subjective** [comment]
@RRethy, whoops I somehow did not catch that, just fixed it

**Comment by RRethy** [comment]
There was a few changes to the code and the structure of the configuration, I made a PR myself but included you as a co-author.

**Pull request closed without merging**
