### PR TITLE
Add queries for the OpenFOAM language

### PR DESCRIPTION
**Pull request by FoamScience**
This is related to nvim-treesitter/nvim-treesitter#2112 and nvim-treesitter/nvim-treesitter-textobjects#143

### CODE REVIEW

**Comment by RRethy** [comment]
I don't know this language so I'll leave maintenance up to you. I won't be personally fixing any bugs.

**Comment by FoamScience** [comment]
Sure, thanks!

**Comment by RRethy** [comment]
**FYI: A new query has been added, `textsubjects-container-inner`, and I have added support for Lua, Ruby, Go, Ruby, Rust.  If you would like support for you language, considering opening a PR. For full information on the query see https://github.com/RRethy/nvim-treesitter-textsubjects/pull/13.

Here is an example of the query on a Lua file:

```lua
function Foo()
  local x = 'Hello, World!' -- <--- linewise selection will start here
  print(x)                  --       |
  print(x)                  --       |
  print(x)                  -- <--- linewise selection will end here
end
```

**Comment by FoamScience** [comment]
Looks interesting! the new query will probably be useful for my language too; Thanks
I'll look into it over this week, maybe open a PR by the weekend; a little busy with swapping countries 😶‍🌫️

**Pull request merged**
